### ISSUE TITLE
It's not compatible with Python3 (at least, with pip3)

### ISSUE THREAD

**Issue by q2dg** [malwaredllc/bamf#2]
It can't be installed

**Comment by malwaredllc** [comment]
Pip installing BAMF is not yet available, you'll need to clone the repo from Github.

1) **Terminal**: Enter the command `git clone https://github.com/malwaredllc/bamf` in your terminal
2) **Browser**: Visit `https://github.com/malwaredllc/bamf` in your browser and click `Download`

**Comment by q2dg** [comment]
You should modify README.md, then
Thanks, anyway
